### ISSUE TITLE
How to get a list of supported maps?

### ISSUE THREAD

**Issue by syaifulnizamyahya** [ineedbots/cod4x_waypoints#1]
I want my sv_mapRotation to have all supported maps.
I find 2 waypoints folder.
https://github.com/ineedbots/cod4x_waypoints/tree/65a344f95388f6d0f0704f3c4517283670bb2818
https://github.com/ineedbots/cod4x_bot_warfare/tree/master/main_shared/maps/mp/bots/waypoints

Which one is the correct one? Do you have sv_mapRotation which already include all supported maps?

Thanks.

**Comment by ineedbots** [comment]
both,

the mod will try to load the .csv, if it cannot find one, it loads gsc
